name: exoplanets
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.7
  - altair
  - pip
  - pyyaml
  - ipykernel
  - pandas
  - django>=2.2
  - black
  - scikit-learn
  - pip:
    - nb_black
    - gremlinpython==3.5.1
    - psycopg2-binary
prefix: C:\Users\william.harding\Anaconda3\envs\exoplanets
