name: exoplanets
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8
  - black
  - cryptography
  - django==3.2.7
  - ipykernel
  - openpyx==3.1.0
  - pandas
  - pip
  - pyyaml
  - scikit-learn
  - pip:
    - nb_black
    - gremlinpython==3.5.1
    - psycopg2-binary==2.9.2
prefix: C:\Users\william.harding\Anaconda3\envs\exoplanets
